baseURL = "https://example.com"
title = "./BLOG"
languageCode = "en"
DefaultContentLanguage = "en" # Change this to change the site's language
theme = "hugo.386"
preserveTaxonomyNames = true

[params]
    # The name to display as main title in the home page
    mainpagetitle = "T.J. Loudon's Blog"

    # The subtitle to display under the title in the home page
    mainpagesubtitle = "Welcome to the BLOG section." 

    # The name to display as main title in the home page
    mainpagedesc = "I don't write too often here, but here's just my blog. It's probably mostly dev/music. Who knows."

    # The name to display in the copyright section in the footer
    copyrightname = "T.J. Loudon 2020 | Theme by JM Fergeau"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.



    # Urls for social networks
    twitter = "https://twitter.com/int_tj"
    github = "https://github.com/Thomascodes"

    # Enables or disables the loading animations. false activates them. Default is false.
    loadfastload = false

    # Sets the speed for the page loading effect. Default is 1.0.
    loadspeedfactor = 1.0

    # Enables or disables the second flyby cursor. Default is false.
    loadonepass = false

[menu]
  # This displays buttons in the navbar to access your contents
  [[menu.main]]
    identifier = "main" # An unique identifier for the button
    name = "Main Site"       # A display name for the button
    url = "http://tjloudon.me"      # The path to the content. It can lead to a single page (like here)
    weight = 10          # A number to order the buttons in the navbar

  [[menu.main]]
    identifier = "posts"
    name = "All posts"
    url = "/post/"       # The path can lead to a content folder too.
    weight = 20

[taxonomies]
category = "categories"
tag = "tags"


[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true